# Generated by Django 3.0.8 on 2020-07-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20200715_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
