# Generated by Django 3.0.8 on 2020-07-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20200718_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
