# Generated by Django 3.0.8 on 2020-07-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_orderitem_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
