# Generated by Django 3.0.8 on 2020-07-19 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20200719_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varientname',
            name='varient',
        ),
        migrations.AddField(
            model_name='varientname',
            name='varient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Varient'),
        ),
    ]
