# Generated by Django 3.0.8 on 2020-07-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_auto_20200719_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varientname',
            name='varient',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.Varient'),
        ),
    ]
