# Generated by Django 3.0.8 on 2020-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20200719_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varient',
        ),
        migrations.AddField(
            model_name='product',
            name='varient',
            field=models.ManyToManyField(to='ecommerce.VarientName'),
        ),
    ]
