# Generated by Django 3.0.8 on 2020-07-19 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_auto_20200719_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='varient',
        ),
        migrations.AddField(
            model_name='varientname',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Product'),
        ),
    ]
