# Generated by Django 3.0.8 on 2020-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_auto_20200719_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ManyToManyField(to='ecommerce.Product'),
        ),
    ]
