# Generated by Django 3.0.8 on 2020-07-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_auto_20200719_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('c', 'consulting'), ('w', 'working_on_it'), ('s', 'shipped')], default='c', max_length=100),
        ),
    ]
