# Generated by Django 3.0.8 on 2020-07-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_auto_20200720_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ManyToManyField(null=True, to='ecommerce.Order'),
        ),
    ]
