# Generated by Django 3.0.8 on 2020-07-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_auto_20200720_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varient',
            name='varient',
        ),
        migrations.AddField(
            model_name='varientname',
            name='varient',
            field=models.ManyToManyField(blank=True, to='ecommerce.Varient'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
    ]
