# Generated by Django 3.0.8 on 2020-07-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_auto_20200721_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='disc',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
    ]
