# Generated by Django 3.0.8 on 2020-07-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0044_auto_20200730_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exeption',
            field=models.CharField(choices=[('s', 'sold'), ('n', 'new')], default='n', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
    ]
