# Generated by Django 3.0.8 on 2020-08-09 14:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0060_auto_20200807_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 15, 45, 32, 205858)),
        ),
        migrations.RemoveField(
            model_name='varientname',
            name='varient',
        ),
        migrations.AddField(
            model_name='varientname',
            name='varient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Varient'),
        ),
    ]
