# Generated by Django 3.0.8 on 2020-08-12 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0066_auto_20200812_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sippingadress',
            old_name='adresse_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='sippingadress',
            old_name='adresse_2',
            new_name='address_2',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 12, 47, 55, 131478)),
        ),
    ]
