# Generated by Django 3.0.8 on 2020-08-14 00:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0078_auto_20200814_0114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SippingAddress',
            new_name='ShippingAddress',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 14, 1, 19, 9, 983979)),
        ),
    ]
