# Generated by Django 3.0.8 on 2020-08-15 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0082_auto_20200814_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='varient_1',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='varient_2',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='varient_3',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='varients',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 13, 43, 6, 387683)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
    ]
