# Generated by Django 3.0.8 on 2020-08-27 23:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import inclusive_django_range_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0100_auto_20200828_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=inclusive_django_range_fields.fields.InclusiveIntegerRangeField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 0, 30, 8, 107529)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
    ]
