# Generated by Django 3.0.8 on 2020-08-27 23:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0101_auto_20200828_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='progress',
            field=models.CharField(choices=[('25', '25%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], default='25', max_length=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 0, 35, 22, 960145)),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
    ]
