# Generated by Django 3.0.8 on 2020-10-01 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0111_auto_20200929_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='after_reduction_total',
            new_name='after_discount_total',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 19, 0, 57, 666050)),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.Order'),
        ),
        migrations.AlterField(
            model_name='varientname',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varient_names', to='ecommerce.Product'),
        ),
        migrations.AlterField(
            model_name='varientname',
            name='varient',
            field=models.ManyToManyField(blank=True, related_name='varient_names', to='ecommerce.Varient'),
        ),
    ]
