# Generated by Django 4.0.2 on 2022-02-05 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0114_auto_20201006_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 18, 14, 27, 959467)),
        ),
    ]
